export const tagTypes = {
  auth: "auth",
  users: "users",
  vendor: "vendor",
  otp: "otp",
  restaurant: "restaurant",
  menuCategory: "menuCategory",
  menu: "menu",
  table: "table",
  booking: "booking",
  admin: "admin",
  favoriteList: "favoriteList",
  files: "files",
  cart: "cart",
  notification: "notification",
  content: "content",
  order: "order",
  wallet: "wallet",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.users,
  tagTypes.vendor,
  tagTypes.otp,
  tagTypes.restaurant,
  tagTypes.menuCategory,
  tagTypes.menu,
  tagTypes.table,
  tagTypes.booking,
  tagTypes.admin,
  tagTypes.favoriteList,
  tagTypes.files,
  tagTypes.cart,
  tagTypes.notification,
  tagTypes.content,
  tagTypes.order,
  tagTypes.wallet,
];
